### ISSUE TITLE
Problème d'enregistrement dans le local storage

### ISSUE THREAD

**Issue by gturyz** [gturyz/ember_tds_2020#1]
### Etapes
Lors de la création d'un developer
### Ressources
https://github.com/gturyz/ember_tds_2020/blob/a123b048a6b4e331c2684739f524cc0ea0fc6990/app/routes/developers/new.js#L5-L11
### Résultat attendu
Enregistrement du nom saisie dans le local storage.
### Résultat obtenu
La valeur undefined s'enregistre.
Ping @jcheron

**Comment by jcheron** [comment]
Ca aurait été encore mieux avec le hbs correspondant:
https://github.com/gturyz/ember_tds_2020/blob/a123b048a6b4e331c2684739f524cc0ea0fc6990/app/templates/developers/new.hbs#L1-L13

Pour la route:
```javascript
import Route from '@ember/routing/route';
import EmberObject from '@ember/object';

export default Route.extend({
   model(){
       return EmberObject.create();
   },
    actions: {
		createNewDeveloper(dev) {
			let developer = this.store.createRecord('developer', {
				name: dev.name
			});
            developer.save().then(()=>this.transitionTo("developers"));
		}
    }
});
```
Dans le template:

```html
 <div class="form-group"> 
     <label for="inputName">Identity</label> 
     <Input class="form-control" @value={{model.name}}/> 
 </div> 
 <a {{action "createNewDeveloper" model}} class="btn btn-success"><i class="fa fa-check-circle"></i> Validate</LinkTo>
```

**Comment by gturyz** [comment]
Merci pour votre réponse.
J'y penserais pour la prochaine, désolé.
Malheureusement, la solution que vous proposez, ne fonctionne pas.
Les enregistrements dans le local storage de la valeur du nom est toujours undefined.

**Comment by jcheron** [comment]
Mettez une ligne `debugger` dans l'action `createNewDeveloper` et regardez la tête du `dev`

**Comment by gturyz** [comment]
J'ai utilisé `debugger` et je n'ai pas trouvé le name que le input est sensé remplir dans le EmberObject.

**Comment by gturyz** [comment]
C'est bon j'avais un soucis de nom de variable. Merci pour votre aide.
